system_configuration:
    groups:
        email_campaign_settings:
            title: oro.campaign.emailcampaign.system_configuration.title

    fields:
        oro_campaign.campaign_sender_email:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            search_type: text
            options:
                label: oro.campaign.emailcampaign.system_configuration.campaign_sender_email
                required: true
                constraints:
                    - NotBlank: ~
                    - Email: ~
        oro_campaign.campaign_sender_name:
            data_type: string
            search_type: text
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            options:
                label: oro.campaign.emailcampaign.system_configuration.campaign_sender_name
                required: true
                constraints:
                    - NotBlank: ~
        oro_campaign.feature_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.campaign.feature_enabled

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            email_configuration:
                                priority: -10
                                children:
                                    email_campaign_settings:
                                        children:
                                            - oro_campaign.campaign_sender_email
                                            - oro_campaign.campaign_sender_name
            marketing:
                children:
                    marketing_setup:
                        children:
                            marketing_settings:
                                children:
                                    marketing_features:
                                        children:
                                            - oro_campaign.feature_enabled
    api_tree:
        email_configuration:
            oro_campaign.campaign_sender_email: ~
            oro_campaign.campaign_sender_name: ~
